name: CI/CD - Build and Deploy SAM application

on:
  push:
    branches:
      - main  # Update with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (update version to use Node.js 20)
        uses: actions/checkout@v2  

      - name: Set up Python (update version to use Node.js 20)
        uses: actions/setup-python@v3 
        with:
          python-version: 3.8 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install awscli  # Install AWS CLI for SAM commands

      - name: Run Python tests
        run: pytest

      - name: Build SAM application
        run: sam build

      - name: Deploy to AWS (if tests pass)
        if: success()  
        run: |
          # Configure AWS credentials using AWS CLI login or environment variables
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1  # Update with your region
          sam deploy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
