name: Upload Website

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{andreahayes-cloudresumechallenge.com}}
        AWS_ACCESS_KEY_ID: ${{AKIATJBDIUY7YWAE7CVI}}
        AWS_SECRET_ACCESS_KEY: ${{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}}
        AWS_REGION: 'us-east-2'
        SOURCE_DIR: 'public_html'